package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.ByteArrayOutputStream;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.19 12:06:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi45 */
  @Test
  public void testRekisteroi45() {    // Kirjailija: 45
    Kirjailija kir1 = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 47", 0, kir1.getKirjailijaId()); 
    kir1.rekisteroi(); 
    Kirjailija kir2 = new Kirjailija(); 
    kir2.rekisteroi(); 
    int n1 = kir1.getKirjailijaId(); 
    int n2 = kir2.getKirjailijaId(); 
    assertEquals("From: Kirjailija line: 53", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testVastaaHarukiMurakami67 */
  @Test
  public void testVastaaHarukiMurakami67() {    // Kirjailija: 67
    ByteArrayOutputStream outContent = new ByteArrayOutputStream(); 
    Kirjailija kir = new Kirjailija(); 
    kir.vastaaHarukiMurakami(1, "Haruki Murakami"); 
    kir.tulosta(outContent); 
    assertEquals("From: Kirjailija line: 73", "1 Haruki Murakami\n", outContent.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse139 */
  @Test
  public void testParse139() {    // Kirjailija: 139
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   |  Haruki Murakami"); 
    assertEquals("From: Kirjailija line: 142", 2, kirjailija.getKirjailijaId()); 
    assertEquals("From: Kirjailija line: 143", "2|Haruki Murakami", kirjailija.toString()); 
  } // Generated by ComTest END
}