package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.14 20:13:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjakokoelmaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Kirjakokoelma: 35
    Kirjakokoelma kirjakokoelma = new Kirjakokoelma(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); 
    assertEquals("From: Kirjakokoelma line: 40", 0, kirjakokoelma.getKirjat()); 
    kirjakokoelma.lisaa(kirja1); assertEquals("From: Kirjakokoelma line: 41", 1, kirjakokoelma.getKirjat()); 
    kirjakokoelma.lisaa(kirja2); 
    assertEquals("From: Kirjakokoelma line: 43", 2, kirjakokoelma.getKirjat()); 
    assertEquals("From: Kirjakokoelma line: 44", kirja1, kirjakokoelma.annaKirja(0)); 
    assertEquals("From: Kirjakokoelma line: 45", kirja2, kirjakokoelma.annaKirja(1)); 
    try {
    assertEquals("From: Kirjakokoelma line: 46", kirja1, kirjakokoelma.annaKirja(3)); 
    fail("Kirjakokoelma: 46 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjakokoelma.lisaa(kirja1); 
    kirjakokoelma.lisaa(kirja1); 
    kirjakokoelma.lisaa(kirja1); 
    try {
    kirjakokoelma.lisaa(kirja1); 
    fail("Kirjakokoelma: 50 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}