package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.14 19:42:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa27 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa27() throws SailoException {    // Kirjat: 27
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjat line: 31", 0, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja2); assertEquals("From: Kirjat line: 33", 2, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 34", kirja1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 35", kirja2, kirjat.anna(1)); 
    try {
    assertEquals("From: Kirjat line: 36", kirja1, kirjat.anna(2)); 
    fail("Kirjat: 36 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja1); 
    try {
    kirjat.lisaa(kirja1); 
    fail("Kirjat: 40 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}