package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 22:08:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetKirjanNimi27 */
  @Test
  public void testGetKirjanNimi27() {    // Kirja: 27
    Kirja kirja = new Kirja(); 
    kirja.vastaaKafkaRannalla(); 
    { String _l_=kirja.getKirjanNimi(),_r_="Kafka rannalla"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 30" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi55 */
  @Test
  public void testRekisteroi55() {    // Kirja: 55
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 57", 0, kirja.getId()); 
    kirja.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int id1 = kirja.getId(); 
    int id2 = kirja2.getId(); 
    assertEquals("From: Kirja line: 63", id2 - 1, id1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString135 */
  @Test
  public void testToString135() {    // Kirja: 135
    Kirja kirja = new Kirja(); 
    kirja.parse("   2  |  4  | Kafka rannalla "); 
    assertEquals("From: Kirja line: 138", true, kirja.toString().startsWith("2|4|Kafka rannalla|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse158 */
  @Test
  public void testParse158() {    // Kirja: 158
    Kirja kirja = new Kirja(); 
    kirja.parse("   1  |  3   | Suuri lammasseikkailu"); 
    assertEquals("From: Kirja line: 161", 1, kirja.getId()); 
  } // Generated by ComTest END
}