package kirjasto.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 22:12:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjakokoelmaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa46 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa46() throws SailoException {    // Kirjakokoelma: 46
    Kirjakokoelma kirjakokoelma = new Kirjakokoelma(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    kirja1.rekisteroi(); kirja2.rekisteroi(); 
    assertEquals("From: Kirjakokoelma line: 51", 0, kirjakokoelma.getKirjat()); 
    kirjakokoelma.lisaa(kirja1); assertEquals("From: Kirjakokoelma line: 52", 1, kirjakokoelma.getKirjat()); 
    kirjakokoelma.lisaa(kirja2); 
    assertEquals("From: Kirjakokoelma line: 54", 2, kirjakokoelma.getKirjat()); 
    assertEquals("From: Kirjakokoelma line: 55", kirja1, kirjakokoelma.annaKirja(0)); 
    assertEquals("From: Kirjakokoelma line: 56", kirja2, kirjakokoelma.annaKirja(1)); 
    try {
    assertEquals("From: Kirjakokoelma line: 57", kirja1, kirjakokoelma.annaKirja(3)); 
    fail("Kirjakokoelma: 57 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjakokoelma.lisaa(kirja1); 
    kirjakokoelma.lisaa(kirja1); 
    kirjakokoelma.lisaa(kirja1); 
    kirjakokoelma.lisaa(kirja1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta127 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta127() throws SailoException {    // Kirjakokoelma: 127
    Kirjakokoelma kirjakokoelma = new Kirjakokoelma(); 
    Kirja kafka = new Kirja(); kafka.vastaaKafkaRannalla(); kafka.rekisteroi(); 
    Kirja kafka1 = new Kirja(); kafka1.vastaaKafkaRannalla(); kafka1.rekisteroi(); 
    Kirjailija haru = new Kirjailija(); haru.vastaaHarukiMurakami(kafka.getId()); 
    Kirjailija haru1 = new Kirjailija(); haru1.vastaaHarukiMurakami(kafka1.getId()); 
    String hakemisto = "testikirjat"; 
    File dir = new File(hakemisto); 
    File ftied  = new File(hakemisto+"/kirjat.dat"); 
    File fhtied = new File(hakemisto+"/kirjailijat.dat"); 
    dir.mkdir(); 
    ftied.delete(); 
    fhtied.delete(); 
    try {
    kirjakokoelma.lueTiedostosta(hakemisto); 
    fail("Kirjakokoelma: 148 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjakokoelma.lisaa(kafka); 
    kirjakokoelma.lisaa(kafka1); 
    kirjakokoelma.lisaa(haru); 
    kirjakokoelma.lisaa(haru1); 
    kirjakokoelma.tallenna(); 
    kirjakokoelma = new Kirjakokoelma(); 
    kirjakokoelma.lueTiedostosta(hakemisto); 
    Collection<Kirja> kaikki = kirjakokoelma.etsi("",-1); 
    Iterator<Kirja> it = kaikki.iterator(); 
    assertEquals("From: Kirjakokoelma line: 160", kafka, it.next()); 
    assertEquals("From: Kirjakokoelma line: 161", kafka1, it.next()); 
    assertEquals("From: Kirjakokoelma line: 162", false, it.hasNext()); 
  } // Generated by ComTest END
}