package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.ByteArrayOutputStream;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 22:09:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testVastaaHarukiMurakami33 */
  @Test
  public void testVastaaHarukiMurakami33() {    // Kirjailija: 33
    ByteArrayOutputStream outContent = new ByteArrayOutputStream(); 
    Kirjailija kir = new Kirjailija(); 
    kir.vastaaHarukiMurakami(1); 
    kir.tulosta(outContent); 
    assertEquals("From: Kirjailija line: 39", "1 Haruki Murakami\n", outContent.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse102 */
  @Test
  public void testParse102() {    // Kirjailija: 102
    Kirjailija kirjailija = new Kirjailija(); 
    kirjailija.parse("   2   |  Haruki Murakami"); 
    assertEquals("From: Kirjailija line: 105", 2, kirjailija.getKirjailijaId()); 
    assertEquals("From: Kirjailija line: 106", "2|Haruki Murakami", kirjailija.toString()); 
  } // Generated by ComTest END
}