package kirjasto.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjasto.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.01 22:11:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta63 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta63() throws SailoException {    // Kirjailijat: 63
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija haru1 = new Kirjailija(); haru1.vastaaHarukiMurakami(1); 
    Kirjailija haru2 = new Kirjailija(); haru2.vastaaHarukiMurakami(1); 
    String tiedNimi = "testikirjat"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    kirjailijat.lueTiedostosta(tiedNimi); 
    fail("Kirjailijat: 73 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjailijat.lisaa(haru1); 
    kirjailijat.lisaa(haru2); 
    kirjailijat.tallenna(); 
    kirjailijat = new Kirjailijat(); 
    kirjailijat.lueTiedostosta(tiedNimi); 
    Iterator<Kirjailija> i = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 80", haru1.toString(), i.next().toString()); 
    assertEquals("From: Kirjailijat line: 81", haru2.toString(), i.next().toString()); 
    assertEquals("From: Kirjailijat line: 82", false, i.hasNext()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator182 */
  @Test
  public void testIterator182() {    // Kirjailijat: 182
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija esim1 = new Kirjailija(1); kirjailijat.lisaa(esim1); 
    Kirjailija esim2 = new Kirjailija(2); kirjailijat.lisaa(esim2); 
    Kirjailija esim3 = new Kirjailija(3); kirjailijat.lisaa(esim3); 
    Iterator<Kirjailija> i2 = kirjailijat.iterator(); 
    assertEquals("From: Kirjailijat line: 192", esim1, i2.next()); 
    assertEquals("From: Kirjailijat line: 193", esim2, i2.next()); 
    assertEquals("From: Kirjailijat line: 194", esim3, i2.next()); 
    try {
    assertEquals("From: Kirjailijat line: 195", esim1, i2.next()); 
    fail("Kirjailijat: 195 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int kirIdt[] = { 1, 2, 3} ; 
    for ( Kirjailija kir:kirjailijat ) {
    assertEquals("From: Kirjailijat line: 201", kirIdt[n], kir.getKirjailijaId()); n++; 
    }
    assertEquals("From: Kirjailijat line: 204", 3, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKirjailija218 */
  @Test
  public void testAnnaKirjailija218() {    // Kirjailijat: 218
    Kirjailijat kirjailijat = new Kirjailijat(); 
    Kirjailija esim1 = new Kirjailija(1); kirjailijat.lisaa(esim1); 
    Kirjailija esim2 = new Kirjailija(2); kirjailijat.lisaa(esim2); 
    Kirjailija esim3 = new Kirjailija(3); kirjailijat.lisaa(esim3); 
    assertEquals("From: Kirjailijat line: 224", esim2, kirjailijat.annaKirjailija(2)); 
    assertEquals("From: Kirjailijat line: 225", esim1, kirjailijat.annaKirjailija(1)); 
  } // Generated by ComTest END
}