package kirjasto.test;
// Generated by ComTest BEGIN
import kirjasto.*;
import java.io.File;
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.19 12:44:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa61 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa61() throws SailoException {    // Kirjat: 61
    Kirjat kirjat = new Kirjat(); 
    Kirja kirja1 = new Kirja(), kirja2 = new Kirja(); 
    assertEquals("From: Kirjat line: 65", 0, kirjat.getLkm()); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja2); assertEquals("From: Kirjat line: 67", 2, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 68", kirja1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 69", kirja2, kirjat.anna(1)); 
    try {
    assertEquals("From: Kirjat line: 70", kirja1, kirjat.anna(2)); 
    fail("Kirjat: 70 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja1); 
    kirjat.lisaa(kirja1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta216 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta216() throws SailoException {    // Kirjat: 216
    Kirjat kirjat = new Kirjat(); 
    Kirja kafka = new Kirja(); kafka.vastaaKafkaRannalla(); 
    Kirja kafka1 = new Kirja(); kafka1.vastaaKafkaRannalla(); 
    String hakemisto = "testikirjat"; 
    String tiedNimi = hakemisto+"/kirjat"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    kirjat.lueTiedostosta(tiedNimi); 
    fail("Kirjat: 233 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kirjat.lisaa(kafka); 
    kirjat.lisaa(kafka1); 
    kirjat.tallenna(); 
    kirjat = new Kirjat();  // Poistetaan vanhat luomalla uusi
    kirjat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Kirja> i = kirjat.iterator(); 
    assertEquals("From: Kirjat line: 240", kafka, i.next()); 
    assertEquals("From: Kirjat line: 241", kafka1, i.next()); 
    assertEquals("From: Kirjat line: 242", false, i.hasNext()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKirjatIterator320 
   * @throws SailoException when error
   */
  @Test
  public void testKirjatIterator320() throws SailoException {    // Kirjat: 320
    Kirjat kirjat = new Kirjat(); 
    Kirja kafka = new Kirja(), kafka1 = new Kirja(); 
    kafka.rekisteroi(); kafka1.rekisteroi(); 
    kirjat.lisaa(kafka); 
    kirjat.lisaa(kafka1); 
    String tulos = " " + kafka.getId() + " " + kafka1.getId(); 
    StringBuffer ids = new StringBuffer(30); 
    for (Iterator<Kirja>  i=kirjat.iterator(); i.hasNext(); ) {
    Kirja kirja = i.next(); 
    ids.append(" "+kirja.getId()); 
    }
    assertEquals("From: Kirjat line: 340", tulos, ids.toString()); 
    Iterator<Kirja>  i=kirjat.iterator(); 
    assertEquals("From: Kirjat line: 343", true, i.next() == kafka); 
    assertEquals("From: Kirjat line: 344", true, i.next() == kafka1); 
    try {
    i.next(); 
    fail("Kirjat: 346 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}