package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.14 19:35:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetKirjanNimi26 */
  @Test
  public void testGetKirjanNimi26() {    // Kirja: 26
    Kirja kirja = new Kirja(); 
    kirja.vastaaKafkaRannalla(); 
    { String _l_=kirja.getKirjanNimi(),_r_="Kafka rannalla"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 29" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi54 */
  @Test
  public void testRekisteroi54() {    // Kirja: 54
    Kirja kirja = new Kirja(); 
    assertEquals("From: Kirja line: 56", 0, kirja.getId()); 
    kirja.rekisteroi(); 
    Kirja kirja2 = new Kirja(); 
    kirja2.rekisteroi(); 
    int id1 = kirja.getId(); 
    int id2 = kirja2.getId(); 
    assertEquals("From: Kirja line: 62", id2 - 1, id1); 
  } // Generated by ComTest END
}