package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.io.ByteArrayOutputStream;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.14 19:57:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testVastaaHarukiMurakami32 */
  @Test
  public void testVastaaHarukiMurakami32() {    // Kirjailija: 32
    ByteArrayOutputStream outContent = new ByteArrayOutputStream(); 
    Kirjailija kir = new Kirjailija(); 
    kir.vastaaHarukiMurakami(1); 
    kir.tulosta(outContent); 
    assertEquals("From: Kirjailija line: 38", "1 Haruki Murakami\n", outContent.toString()); 
  } // Generated by ComTest END
}